FROM tensorflow/tensorflow:2.15.0-gpu

RUN apt-get update && apt-get install -y \
    wget \
    git \
    cmake \
    build-essential \
    automake \
    xz-utils \
    pigz \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    samtools \
    parallel \
    libboost-graph-dev \
    libssl-dev \
    libdeflate-dev \
    && rm -rf /var/lib/apt/lists/*

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/bin

WORKDIR /opt/bin

RUN pip3 install --no-cache-dir whatshap cffi

COPY . .

RUN cd /opt/bin/preprocess/realign && \
    g++ -std=c++14 -O1 -shared -fPIC -o realigner ssw_cpp.cpp ssw.c realigner.cpp && \
    g++ -std=c++11 -shared -fPIC -o debruijn_graph -O3 debruijn_graph.cpp && \
    wget http://www.bio8.cs.hku.hk/clair3/clair3_models/clair3_models.tar.gz -P /opt/models && \
    tar -zxvf /opt/models/clair3_models.tar.gz -C /opt/models && \
    rm /opt/models/clair3_models.tar.gz && \
    cd /opt/bin && make PREFIX=/usr/local PYTHON=/usr/bin/python3 && \
    rm -rf /opt/bin/samtools-* /opt/bin/longphase-* && \
    cd /opt/bin && wget -q https://downloads.python.org/pypy/pypy3.9-v7.3.8-linux64.tar.bz2 && \
    tar -xjf pypy3.9-v7.3.8-linux64.tar.bz2 && \
    rm pypy3.9-v7.3.8-linux64.tar.bz2 && \
    ln -sf /opt/bin/pypy3.9-v7.3.8-linux64/bin/pypy3 /opt/bin/pypy3
